version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: huarongdao_postgres
    restart: always
    environment:
      POSTGRES_DB: game_huarongdao
      POSTGRES_USER: admin.lanlic
      POSTGRES_PASSWORD: 98605831aAqQ
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"  # 避免端口冲突
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin.lanlic -d game_huarongdao"]
      interval: 30s
      timeout: 10s
      retries: 3

  game:
    build: .
    container_name: huarongdao_game
    restart: always
    ports:
      - "6001:80"  # 使用6001端口避免冲突
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin.lanlic:98605831aAqQ@postgres:5432/game_huarongdao
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
